import Head from "next/head";
import PageSpeedInsight from "@/components/page-speed-insight";
import {  infos } from "../../data/infos";
import { DELAY_BETWEEN_RUN_SEC, NUM_RUNS } from "@/utils/constants";

export default function Home() {
  return (
    <>
      <Head>
        <title>PSI App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageSpeedInsight
          numRuns={NUM_RUNS}
          delayBetweenRunSec={DELAY_BETWEEN_RUN_SEC}
          infos={infos}
        />
      </main>
    </>
  );
}
