import Head from "next/head";
import PageSpeedInsight from "@/components/page-speed-insight";
import { infos } from "../../data/infos";
import { DELAY_BETWEEN_RUN_SEC, NUM_RUNS } from "@/utils/client/constants";

const debug = false;

export default function Home() {
  const elemPsi = debug ? (
    <PageSpeedInsight
      numRuns={2}
      delayBetweenRunSec={1}
      infos={infos.slice(0, 3)}
    />
  ) : (
    <PageSpeedInsight
      numRuns={NUM_RUNS}
      delayBetweenRunSec={DELAY_BETWEEN_RUN_SEC}
      infos={infos}
    />
  );

  return (
    <>
      <Head>
        <title>PSI App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{elemPsi}</main>
    </>
  );
}
